model_provider = "openai-custom"
model = "gpt-4.1"
disable_response_storage = true

[model_providers.openai-custom]
name = "openai-custom"
base_url = "https://api.openai.com/v1"
wire_api = "responses"
requires_openai_auth = true

[windows]
sandbox = "elevated"

[projects.'c:\users\user\ai-interviewer']
trust_level = "trusted"