"""Outbound interfaces owned by the application layer."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol

from interview_platform.domain.models import Interview


class InterviewRepository(Protocol):
    def create(self, interview: Interview) -> None: ...

    def save(self, interview: Interview) -> None: ...

    def get_by_id(self, interview_id: str) -> Interview | None: ...

    def get_by_token_digest(self, token_digest: str) -> Interview | None: ...

    def list_interviews(self) -> list[Interview]: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class IdentifierGenerator(Protocol):
    def new_id(self) -> str: ...


class TokenGenerator(Protocol):
    def new_token(self) -> str: ...


@dataclass(frozen=True, slots=True)
class CapturedAnswer:
    capture_kind: str
    content: str
    media_reference: str | None = None


class AnswerCapture(Protocol):
    def capture(self, content: str) -> CapturedAnswer: ...


class HiringRepository(Protocol):
    """Persistence operations used by vacancy-aware application services."""

    def save_framework(self, payload: dict[str, Any]) -> None: ...

    def get_framework(self) -> dict[str, Any] | None: ...

    def save_vacancy(self, payload: dict[str, Any]) -> None: ...

    def get_vacancy(self, vacancy_id: str) -> dict[str, Any] | None: ...

    def list_vacancies(self) -> list[dict[str, Any]]: ...

    def save_context_source(self, payload: dict[str, Any]) -> None: ...

    def get_context_source(self, source_id: str) -> dict[str, Any] | None: ...

    def list_context_sources(self, vacancy_id: str) -> list[dict[str, Any]]: ...

    def save_profile(self, payload: dict[str, Any]) -> None: ...

    def get_profile(self, profile_id: str) -> dict[str, Any] | None: ...

    def list_profiles(self, vacancy_id: str) -> list[dict[str, Any]]: ...

    def save_snapshot(self, payload: dict[str, Any]) -> None: ...

    def get_snapshot(self, snapshot_id: str) -> dict[str, Any] | None: ...

    def list_snapshots(self, vacancy_id: str) -> list[dict[str, Any]]: ...

    def assign_interview(
        self,
        interview_id: str,
        vacancy_id: str,
        snapshot_id: str,
        created_at: str,
    ) -> None: ...

    def get_assignment(self, interview_id: str) -> dict[str, Any] | None: ...

    def list_assignments(self, vacancy_id: str) -> list[dict[str, Any]]: ...

    def save_assessment_run(self, payload: dict[str, Any]) -> None: ...

    def get_assessment_run(self, run_id: str) -> dict[str, Any] | None: ...

    def get_assessment_by_idempotency(self, key: str) -> dict[str, Any] | None: ...

    def list_assessment_runs(self, interview_id: str) -> list[dict[str, Any]]: ...

    def save_ranking_snapshot(self, payload: dict[str, Any], idempotency_key: str) -> None: ...

    def get_ranking_snapshot(self, snapshot_id: str) -> dict[str, Any] | None: ...

    def list_ranking_snapshots(self, vacancy_id: str) -> list[dict[str, Any]]: ...

    def get_ranking_by_idempotency(self, key: str) -> dict[str, Any] | None: ...

    def save_decision(self, payload: dict[str, Any], idempotency_key: str) -> None: ...

    def get_decision_by_idempotency(self, key: str) -> dict[str, Any] | None: ...

    def list_decisions(self, interview_id: str) -> list[dict[str, Any]]: ...

    def save_feedback_entry(self, payload: dict[str, Any]) -> None: ...

    def get_feedback_entry(self, entry_id: str) -> dict[str, Any] | None: ...

    def list_feedback_entries(self, interview_id: str) -> list[dict[str, Any]]: ...

    def get_idempotent_result(self, key: str, scope: str) -> dict[str, Any] | None: ...

    def save_idempotent_result(self, key: str, scope: str, payload: dict[str, Any]) -> None: ...
