import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { getInterviewResult } from '../api';
import { InterviewResultDetail } from '../types';

const CandidateDetails: React.FC = () => {
  const { vacancyId = '', candidateId = '' } = useParams(); const navigate = useNavigate();
  const [result, setResult] = useState<InterviewResultDetail | null>(null); const [error, setError] = useState('');
  useEffect(() => { getInterviewResult(vacancyId, candidateId).then(setResult).catch(() => setError('Не удалось загрузить сохранённые результаты интервью.')); }, [vacancyId, candidateId]);
  return <><nav className="navbar navbar-light bg-white shadow-sm"><div className="container"><span className="navbar-brand">AI Интервьюер</span><button className="btn btn-sm btn-outline-secondary" onClick={() => navigate(`/leaderboard/${vacancyId}`)}>← К интервью</button></div></nav><main className="container my-4" style={{ maxWidth: 1180 }}>
    {error && <div className="alert alert-danger">{error}</div>}{!result && !error && <p className="text-muted">Загружаем материалы…</p>}
    {result && <><section className="card shadow-sm mb-4"><div className="card-body d-flex flex-wrap justify-content-between gap-3"><div><small className="text-muted">Кандидат</small><h4>{result.summary.candidate_alias || 'Кандидат без имени'}</h4></div><div><small className="text-muted">Вакансия</small><h5>{result.vacancy_title}</h5></div><div><small className="text-muted">Оценка</small><h5>{result.summary.score === null ? 'Не рассчитана' : `${result.summary.score}%`}</h5></div></div></section><div className="row g-4">
      <div className="col-lg-5"><section className="card shadow-sm h-100"><div className="card-body"><h5>Запись интервью</h5><p className="text-muted">{result.recording_duration_ms ? `${Math.round(result.recording_duration_ms / 1000)} с` : 'Длительность уточняется'} · {result.media.length} фрагментов</p>{result.media.length ? result.media.map((clip) => <video key={clip.sequence} className="w-100 rounded mb-2 bg-dark" controls preload="metadata" src={clip.url} />) : <div className="alert alert-light">Подтверждённых видеофрагментов пока нет.</div>}<h6 className="mt-4">События проверки</h6>{result.monitoring_events.length ? result.monitoring_events.map((event) => <div className="small border rounded p-2 mb-2" key={event.id}>{event.kind}: {event.started_at_ms / 1000}–{event.ended_at_ms / 1000} с · {event.review_status}{event.evidence_url && <> · <a href={event.evidence_url}>фрагмент</a></>}</div>) : <p className="text-muted small">Событий нет.</p>}</div></section></div>
      <div className="col-lg-7"><section className="card shadow-sm h-100"><div className="card-body"><h5>Ответы и расшифровка</h5>{result.answers.length ? result.answers.map((answer, index) => <article className="border-bottom py-3" key={answer.response_id}><small className="text-muted">Вопрос {index + 1}{answer.is_follow_up ? ' · уточнение' : ''} · {answer.start_offset_ms === null ? 'нет временной отметки' : `${answer.start_offset_ms / 1000}–${(answer.end_offset_ms || 0) / 1000} с`}</small><h6 className="mt-1">{answer.question_text}</h6>{answer.transcription_status === 'completed' ? <p>{answer.transcript_text || 'Речь не обнаружена.'}</p> : <p className={answer.transcription_status === 'failed' ? 'text-danger' : 'text-muted'}>Расшифровка: {answer.transcription_status}</p>}{answer.timed_out && <span className="badge bg-warning text-dark mb-2">Завершено по таймеру</span>}{answer.code && <><div className="small text-muted">Код · {answer.code.language}</div><pre className="bg-dark text-light rounded p-3 overflow-auto"><code>{answer.code.source_code}</code></pre></>}</article>) : <p className="text-muted">Ответов пока нет.</p>}</div></section></div>
    </div></>}
  </main></>;
};
export default CandidateDetails;
